MiniSurveys.Web/Models/ResultViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using MiniSurveys.Domain.Modals;

namespace MiniSurveys.Web.Models
{
    public class ResultViewModel
    {
        public ResultViewModel()
        {

        }

        public ResultViewModel(ICollection<Department> departments, string surveyName, int id)
        {
            DepartmentsSelectList = new List<SelectListItem>();

            foreach (Department item in departments)
                DepartmentsSelectList.Add(new SelectListItem() { Value = item.Id.ToString(), Text = item.Name });

            SelectedDepartment = DepartmentsSelectList.ElementAt(0);
            SurveyName = surveyName;
            Id = id;
        }

        public int Id { get; set; }
        public string SurveyName { get; set; }
        public SelectListItem SelectedDepartment { get; set; }
        public List<SelectListItem> DepartmentsSelectList { get; set; }
    }
}

MiniSurveys.Web/Models/Survey/AnswerViewModel.cs
using MiniSurveys.Domain.Modals;

namespace MiniSurveys.Web.Models.Survey
{
    public class AnswerViewModel
    {
        public AnswerViewModel(Answer answer, int number)
        {
            Id = answer.Id;
            Title = answer.Title;
            if (answer.Media != null)
                Media = new MediaViewModel(answer.Media);
            Number = number;
        }

        public AnswerViewModel()
        {

        }

        public int Id { get; init; }

        public string? Title { get; init; }

        public bool IsTitle => !String.IsNullOrWhiteSpace(Title);

        public MediaViewModel? Media { get; init; }

        public bool IsMedia => Media != null;

        public int Number { get; init; }

        public bool isVote { get; set; }
    }
}

MiniSurveys.Web/Models/Survey/ChartItem.cs
namespace MiniSurveys.Web.Models.Survey
{
    public class ChartItem
    {
        public ChartItem()
        {

        }
        public ChartItem(int value, string title)
        {
            Value = value;
            Title = title;
        }

        public int Value { get; set; }
        public string Title { get; set; }
    }
}

MiniSurveys.Web/Models/Survey/MediaViewModel.cs
using MiniSurveys.Domain.Modals;
using MiniSurveys.Domain.Modals.Enums;

namespace MiniSurveys.Web.Models.Survey
{
    public class MediaViewModel
    {
        public MediaViewModel()
        {

        }

        public MediaViewModel(Media media)
        {
            Id = media.Id;
            Url = media.Url;
            Title = media.Title;
            Type = media.Type;
        }

        public MediaViewModel(Media media, int number, int maxNumber)
        {
            Id = media.Id;
            Url = media.Url;
            Title = media.Title;
            Type = media.Type;
            Number = number;
            MaxNumber = maxNumber;
        }

        public int Id { get; init; }
        public string Url { get; init; } = null!;

        public string? Title { get; init; }

        public TypeMedia Type { get; set; }

        public int? Number { get; init; }

        public int? MaxNumber { get; init; }
    }
}

MiniSurveys.Web/Models/Survey/NewSurvey/NewAnswerViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using MiniSurveys.Domain.Extensions;
using MiniSurveys.Domain.Modals.Enums;
using System.ComponentModel.DataAnnotations;

namespace MiniSurveys.Web.Models.Survey.NewSurvey
{
    public class NewAnswerViewModel
    {
        public NewAnswerViewModel()
        {
            TypeSelectedListMedia = new List<SelectListItem>();
            TypeSelectedListMedia.Add(new SelectListItem
            {
                Text = TypeMedia.Image.GetEnumDisplayName(),
                Value = ((int)TypeMedia.Image).ToString()
            });
            TypeSelectedListMedia.Add(new SelectListItem
            {
                Text = TypeMedia.Video.GetEnumDisplayName(),
                Value = ((int)TypeMedia.Video).ToString()
            });
            SelectedTypeMedia = TypeSelectedListMedia.ElementAt(0);
        }

        [Required(ErrorMessage = "Не указан текст ответа")]
        public string AnswerTitle { get; set; }
        [ValidateNever]
        public string? SignatureMedia { get; set; }
        [ValidateNever]
        public SelectListItem SelectedTypeMedia { get; set; }
        [ValidateNever]
        public ICollection<SelectListItem> TypeSelectedListMedia { get; set; }
        [ValidateNever]
        public string? LinkMedia { get; set; }
        public bool IsActive { get; set; }
    }
}

MiniSurveys.Web/Models/Survey/NewSurvey/NewMediaViewModel.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using MiniSurveys.Domain.Extensions;
using MiniSurveys.Domain.Modals.Enums;
using System.ComponentModel.DataAnnotations;

namespace MiniSurveys.Web.Models.Survey.NewSurvey
{
    public class NewMediaViewModel
    {
        [Required(ErrorMessage = "Не указана подпись мультимедия")]
        public string Signature { get; set; }
        [ValidateNever]
        public SelectListItem SelectedType { get; set; }
        [ValidateNever]
        public ICollection<SelectListItem> TypeSelectedList { get; set; }
        [Required(ErrorMessage = "Укажите cсылку на мультимедия")]
        public string Link { get; set; }

        public NewMediaViewModel()
        {
            TypeSelectedList = new List<SelectListItem>();
            TypeSelectedList.Add(new SelectListItem 
            { 
                Text = TypeMedia.Image.GetEnumDisplayName(), 
                Value = ((int)TypeMedia.Image).ToString()
            });
            TypeSelectedList.Add(new SelectListItem 
            { 
                Text = TypeMedia.Video.GetEnumDisplayName(), 
                Value = ((int)TypeMedia.Video).ToString() 
            });
            SelectedType = TypeSelectedList.ElementAt(0);
        }
    }
}

MiniSurveys.Web/Models/Survey/NewSurvey/NewQuestionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MiniSurveys.Web.Models.Survey.NewSurvey
{
    public class NewQuestionViewModel
    {
        public NewQuestionViewModel()
        {
            Medias = new List<NewMediaViewModel>();
            Answers = new List<NewAnswerViewModel>();
        }

        [Required(ErrorMessage = "Не указан текст вопроса")]
        public string QuestionTitle { get; set; }
        public IList<NewMediaViewModel> Medias { get; set; }
        public IList<NewAnswerViewModel> Answers { get; set; }
    }
}

MiniSurveys.Web/Models/Survey/QuestionResultData.cs
namespace MiniSurveys.Web.Models.Survey
{
    public class QuestionResultData
    {
        public string Title { get; set; }
        public ICollection<ChartItem> Answers { get; set; }
    }
}

MiniSurveys.Web/Controllers/SurveyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MiniSurveys.Domain.Data;
using MiniSurveys.Domain.Modals;
using MiniSurveys.Web.Helpers;
using MiniSurveys.Web.Models;
using MiniSurveys.Web.Models.Survey;
using OfficeOpenXml;
using OfficeOpenXml.Drawing.Chart;
using OfficeOpenXml.Drawing.Chart.Style;
using OfficeOpenXml.Style;
using System.Drawing;
using System.Security.Claims;

namespace MiniSurveys.Web.Controllers
{
    [Authorize]
    public class SurveyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public SurveyController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<ActionResult> Index(bool isActive = true, string? stringSearch = "")
        {
            IEnumerable<Survey> searchResult;

            if (isActive)
                searchResult = await _context.Surveys.Where(x => x.EndTime > DateTime.Now && EF.Functions.Like(x.Title, $"%{stringSearch}%")).AsNoTracking().ToArrayAsync();
            else
                searchResult = await _context.Surveys.Where(x => x.EndTime <= DateTime.Now && EF.Functions.Like(x.Title, $"%{stringSearch}%")).AsNoTracking().ToArrayAsync();

            return View(searchResult);
        }

        [Route("[controller]/{action}")]
        [HttpGet]
        public async Task<ActionResult> GetSurveyListPartial(bool isActive, string stringSearch)
        {
            IEnumerable<Survey> searchResult;

            if (isActive)
                searchResult = await _context.Surveys.Where(x => x.EndTime > DateTime.Now && EF.Functions.Like(x.Title, $"%{stringSearch}%")).AsNoTracking().ToArrayAsync();
            else
                searchResult = await _context.Surveys.Where(x => x.EndTime <= DateTime.Now && EF.Functions.Like(x.Title, $"%{stringSearch}%")).AsNoTracking().ToArrayAsync();

            return PartialView("SurveyListPartial", searchResult);
        }

        [Route("[controller]/{id}")]
        [HttpGet]
        public async Task<ActionResult> Survey(int id)
        {
            string nameKey = $"survey_{this.User.FindFirst(ClaimTypes.NameIdentifier).Value}";

            if (HttpContext.Session.Keys.Contains(nameKey))
            {
                var model = HttpContext.Session.Get<SurveyViewModel>(nameKey);
                return View(model);
            }

            var survey = await _context.Surveys.Include(x => x.Questions)
                                                            .ThenInclude(n => n.Answers)
                                                                .ThenInclude(am => am.Media)
                                                .Include(x => x.Questions)
                                                            .ThenInclude(m => m.Media)
                                                .AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);


            if (survey != null)
            {
                var viewModel = new SurveyViewModel(survey);
                HttpContext.Session.Set<SurveyViewModel>(nameKey, viewModel);
                return View(viewModel);
            }
            else
            {
                return NotFound();
            }
        }

        [Route("[controller]/{action}")]
        [HttpGet]
        public async Task<ActionResult> GetQuestion(bool isNext, IEnumerable<bool> answers)
        {
            string nameKey = $"survey_{this.User.FindFirst(ClaimTypes.NameIdentifier).Value}";

            var model = HttpContext.Session.Get<SurveyViewModel>(nameKey);

            for (int i = 0; i < answers.Count(); i++)
            {
                if (answers.ElementAt(i) == true)
                    model!.GetQuestion().OnVote(i);
            }

            if (isNext)
            {
                if (model!.isNext())
                {
                    model.Next();
                }
            }
            else
            {
                if (model!.isBack())
                {
                    model.Back();
                }
            }
            HttpContext.Session.Set<SurveyViewModel>(nameKey, model);

            return await Task.FromResult(PartialView("QuestionPartial", model));
        }

        [Route("[controller]/{action}")]
        [HttpGet]
        public async Task<ActionResult> Save(IEnumerable<bool> answers)
        {
            var user = await _userManager.GetUserAsync(User);

            string nameKey = $"survey_{this.User.FindFirst(ClaimTypes.NameIdentifier).Value}";

            var model = HttpContext.Session.Get<SurveyViewModel>(nameKey);

            for (int i = 0; i < answers.Count(); i++)
            {
                if (answers.ElementAt(i) == true)
                    model!.GetQuestion().OnVote(i);
            }

            List<QuestionResult> questionResults = new List<QuestionResult>();

            foreach (QuestionViewModel question in model.Questions)
            {
                List<AnswerResult> answerResults = new List<AnswerResult>();

                foreach (AnswerViewModel answer in question.Answers)
                {
                    if (answer.isVote)
                        answerResults.Add(new AnswerResult()
                        {
                            AnswerId = answer.Id,
                        });
                }

                var tmp = new QuestionResult()
                {
                    QuestionId = question.Id,
                    AnswerResults = answerResults,
                };
                questionResults.Add(tmp);
            }

            var result = new SurveyResult()
            {
                UserId = user.Id,
                SurveyId = model.Id,
                DateTime = DateTime.Now,
                QuestionResults = questionResults,
            };

            HttpContext.Session.Clear();

            _context.SurveyResults.Add(result);
            _context.SaveChanges();

            return base.Content("/");
        }

        public async Task<ActionResult> ResultsAsync(int id)
        {
            User user = await _userManager.GetUserAsync(User);
            user = _context.Users.Include(u => u.Department).Single(u => u.Id == user.Id);
            string roles = (await _userManager.GetRolesAsync(user)).ElementAt(0);
            var allDepartmentItem = new Department() { Name = "По всем отделам", Id = 0 };
            var allDepartments = _context.Departments.AsNoTracking().ToArray();
            var surveyName = _context.Surveys.Single(s => s.Id == id).Title;

            ICollection<Department> departments = roles switch
            {
                RoleNames.Employee => new List<Department>() { allDepartmentItem },
                RoleNames.Head => new List<Department>() { allDepartmentItem, allDepartments.Single(d => d.Id == user.Department.Id) },
                RoleNames.Administrator => new List<Department>(allDepartments) { allDepartmentItem },
            };
            departments = departments.OrderBy(d => d.Id).ToArray();

            var model = new ResultViewModel(departments, surveyName, id);

            return View(model);
        }

        [Route("[controller]/{action}")]
        [HttpGet]
        public async Task<ActionResult> GetResult(int id, int fillter)
        {
            ResultData model = await GetResultDataAsync(id, fillter);

            return Json(model);
        }

        [Route("[controller]/{action}")]
        public async Task<ActionResult> ExportToExcel(ResultViewModel viewModel)
        {
            char[] alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".ToCharArray();
            int row = 4;
            int heightRow = 15;
            int fillter = int.Parse(viewModel.SelectedDepartment.Value);
            string surveyedUsersTitle = "Количество прошедших";
            string departmentTitle = fillter switch
            {
                1 => $" по {DepartmentNames.Hr}",
                2 => $" по {DepartmentNames.Dev}",
                3 => $" по {DepartmentNames.Test}",
                _ => "",
            };
            ResultData model = await GetResultDataAsync(viewModel.Id, fillter);
            var package = new ExcelPackage();
            var workSheet = package.Workbook.Worksheets.Add("Результаты опроса");

            workSheet.Cells["A1:N1"].Merge = true;
            workSheet.Cells["A1"].Value = "Результаты опроса " + model.Title + departmentTitle;
            workSheet.Cells["A1"].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
            workSheet.Cells["A1"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            workSheet.Cells["A1"].Style.Font.Bold = true;
            workSheet.Cells["A1"].Style.Font.Size = 20;

            workSheet.Cells["A3:D3"].Merge = true;
            workSheet.Cells["A3"].Value = surveyedUsersTitle;
            workSheet.Cells["A3"].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
            workSheet.Cells["A3"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
            workSheet.Cells["A3:D3"].Style.Border.Top.Style = ExcelBorderStyle.Thin;
            workSheet.Cells["A3:D3"].Style.Border.Right.Style = ExcelBorderStyle.Thin;
            workSheet.Cells["A3:D3"].Style.Border.Left.Style = ExcelBorderStyle.Thin;
            workSheet.Cells["A3:D3"].Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
            workSheet.Cells["A3"].Style.Font.Bold = true;
            workSheet.Cells["A3"].Style.Font.Size = 14;

            for (int i = 0; i <= model.SurveyedUsers.Count; i++)
            {
                workSheet.Cells[$"A{4 + i}:B{4 + i}"].Merge = true;
                workSheet.Cells[$"C{4 + i}:D{4 + i}"].Merge = true;
            }
            List<string> listHeader = new List<string>()
            {

MiniSurveys.Web/ViewComponents/ElementAnswerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniSurveys.Web.Models.Survey;

namespace MiniSurveys.Web.ViewComponents
{
    public class ElementAnswerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(AnswerViewModel answer)
        {
            return Task.FromResult((IViewComponentResult)View(answer));
        }
    }
}

MiniSurveys.Web/ViewComponents/SliderItemViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniSurveys.Web.Models.Survey;

namespace MiniSurveys.Web.ViewComponents
{
    public class SliderItemViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(MediaViewModel media)
        {
            return await Task.FromResult((IViewComponentResult)View(media));
        }
    }
}

MiniSurveys.Web/Views/Survey/Index.cshtml
@model IEnumerable<MiniSurveys.Domain.Modals.Survey>

@{
    ViewBag.Title = "Опросы";
}

<div class="main-body">
    <form class="main__header">
        <div class="main-body__title title">
            <h1>Меню опросов</h1>
        </div>
        <div class="main__sort">
            <div class="main__radio radio-button">
                <input checked name="isActive" id="1" class="radio-button__input" type="radio" value="true">
                <label for="1">Активный</label>
            </div>
            <div class="main__radio radio-button">
                <input name="isActive" id="2" class="radio-button__input" type="radio" value="false">
                <label for="2">Завершенные</label>
            </div>
        </div>
        <div class="main__searchandbutton">
            <div></div>
            <div class="main__search">
                <input type="text" id="search">
                <img src="img/search.svg" alt="">
            </div>
        </div>
    </form>
    <div id="survey-list" class="main__list">
        @await Html.PartialAsync("SurveyListPartial", Model)
    </div>
</div>

MiniSurveys.Web/Views/Survey/QuestionPartial.cshtml
@using MiniSurveys.Web.Helpers
@model MiniSurveys.Web.Models.Survey.SurveyViewModel

<div class="qustion__body">
    <div class="question__number">
        <span>@Model.CurrentQuestion</span>
        <span>/</span>
        <span>@Model.Questions.Count()</span>
        <span>&nbsp;вопрос</span>
    </div>
    @if (!String.IsNullOrWhiteSpace(Model.GetQuestion().Title))
    {
        <div class="question_title title">@Model.GetQuestion().Title</div>
    }
</div>
<div class="answer">
    <form class="answer__body">
        @if (Model.GetQuestion().IsMedia)
        {
            <div class="slider">
                @foreach (var item in Model.GetQuestion().Media)
                {
                    @await Component.InvokeAsync("SliderItem", item)
                }
                <div class="slider__footer">
                    <a class="prev">&#10094;</a>
                    <a class="next">&#10095;</a>
                </div>
            </div>

            <br>
            <div class="slider-menu">
                @for (int i = 1; i <= Model.GetQuestion().Media.Count; i++)
                {
                    if (i == 1)
                    {
                        <span class="dot active" id="picture_@i"></span>
                    }
                    else
                    {
                        <span class="dot" id="picture_@i"></span>
                    }
                }
            </div>
        }
        <ul class="answer__list">
            @foreach (var item in Model.GetQuestion().Answers)
            {
                @await Component.InvokeAsync("ElementAnswer", item)
            }
        </ul>
        <div class="answer__footer">
            <button class="answer__button" id="button_left" @Html.isDisableButton(!Model.isBack())>
                <img src="~/img/ArrowLeft.svg" alt="">
            </button>

            @if(Model.CurrentQuestion == Model.Questions.Count())
            {
                <button class="answer__button" id="button_save">Отправить</button>
            }
            else
            {
                <button class="answer__button" id="button_rigth">
                    <img src="~/img/ArrowRigth.svg" alt="">
                </button>
            }
        </div>
    </form>
</div>

MiniSurveys.Web/Views/Survey/Results.cshtml
@model ResultViewModel

<h1 class="main__title title">@Model.SurveyName</h1>
<div class="result">
    <form class="result__header" asp-controller="Survey" asp-action="ExportToExcel">
        <div action="" class="result__fillter" id="@Model.Id">
            <select asp-for="SelectedDepartment.Value" asp-items="Model.DepartmentsSelectList" id="combobox">
            </select>
            <input type="button" value="Применить" id="button-apply"></input>
        </div>
        <input class="display-none" asp-for="Id" id="user-surname" type="text">
        <div class="result__excel-button">
            <input type="submit" value="Импорт в Excel" id="button-export">
        </div>
    </form>
    <div class="result__main-header">
        <h3>Количество прошедших</h3>
    </div>
    <div class="result__main">
        
        <div class="result__diagramma">
            <canvas id="myChart1"></canvas>
        </div>
        
        <div class="result__gistogramma" id="barCharts"></div>
    </div>
</div>

MiniSurveys.Web/Views/Survey/Survey.cshtml
@model MiniSurveys.Web.Models.Survey.SurveyViewModel

<h1 class="main__title title">Прохождение опроса</h1>

<div class="question">
    @await Html.PartialAsync("QuestionPartial", Model)
</div>