MiniSurveys.Web/Models/UserView/UserViewModel.cs
using Microsoft.AspNetCore.Identity;
using MiniSurveys.Domain.Modals;

namespace MiniSurveys.Web.Models.UserView
{
    public class UserViewModel
    {
        public UserViewModel(User user)
        {
            UserName = user.UserName;
            Name = user.Name;
            Surname = user.Surname;
            Patronymic = user.Patronymic;
            Email = user.Email;
            Phone = user.PhoneNumber;
            Department = user.Department;
        }

        public static async Task<UserViewModel> Initialize(User user, UserManager<User> userManager)
        {
            var model = new UserViewModel(user);
            string role = (await userManager.GetRolesAsync(user)).ElementAt(0);
            model.Role = role;

            return model;
        }

        public string UserName { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public string Patronymic { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public Department Department { get; set; }

        public string Role { get; set; }
    }
}

MiniSurveys.Web/Models/UserViewModel.cs
using Microsoft.AspNetCore.Identity;
using MiniSurveys.Domain.Modals;

namespace MiniSurveys.Web.Models
{
    public class UserViewModel
    {
        public UserViewModel(User user)
        {
            UserName = user.UserName;
            Name = user.Name;
            Surname = user.Surname;
            Patronymic = user.Patronymic;
            Email = user.Email;
            Phone = user.PhoneNumber;
            Department = user.Department;
        }

        public static async Task<UserViewModel> Initialize(User user, UserManager<User> userManager)
        {
            var model = new UserViewModel(user);
            string role = (await userManager.GetRolesAsync(user)).ElementAt(0);
            model.Role = role;

            return model;
        }

        public string UserName { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public string Patronymic { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public Department Department { get; set; }

        public string Role { get; set; }
    }
}

MiniSurveys.Web/ViewComponents/ElementSurveyViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniSurveys.Domain.Modals;

namespace MiniSurveys.Web.ViewComponents
{
    public class ElementSurveyViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(Survey survey)
        {
            return Task.FromResult((IViewComponentResult)View(survey));
        }
    }
}

MiniSurveys.Web/ViewComponents/RowUserViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiniSurveys.Web.Models.UserView;

namespace MiniSurveys.Web.ViewComponents
{
    public class RowUserViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(UserViewModel users)
        {
            return Task.FromResult((IViewComponentResult)View(users));
        }
    }
}

MiniSurveys.Web/Views/Admin/Index.cshtml
@model IEnumerable<MiniSurveys.Domain.Modals.Survey>

@{
    ViewBag.Title = "Управление опросами";
}

<div class="main-body">
    <form class="main__header">
        <div class="main-body__title title">
            <h1>Меню опросов</h1>
        </div>
        <div class="main__sort">
            <div class="main__radio radio-button">
                <input checked name="isActive" id="1" class="radio-button__input" type="radio" value="true">
                <label for="1">Активный</label>
            </div>
            <div class="main__radio radio-button">
                <input name="isActive" id="2" class="radio-button__input" type="radio" value="false">
                <label for="2">Завершенные</label>
            </div>
        </div>
        <div class="main__searchandbutton">
            <a class="main__add" href="@Url.Action("CreateSurvey", "Admin")">+ Добавить</a>
            <div class="main__search">
                <input type="text" id="search">
                <img src="img/search.svg" alt="">
            </div>
        </div>
    </form>
    <div id="survey-list" class="main__list">
        @await Html.PartialAsync("SurveyListPartial", Model)
    </div>
</div>

MiniSurveys.Web/Views/Admin/SurveyListPartial.cshtml
@model IEnumerable<MiniSurveys.Domain.Modals.Survey>

@{
    foreach (var item in Model)
    {
        @await Component.InvokeAsync("ElementSurvey", item)
    }
}

MiniSurveys.Web/Views/Admin/UserCreatePartial.cshtml
@model MiniSurveys.Web.Models.UserView.UserCreateViewModel

@{
    Layout = null;
}

<div class="user__header">
    <span class="user__title">Создание</span>
</div>
<form class="user__body" asp-action="UserCreatePartial" method="post" enctype="multipart/form-data" onsubmit="return jQueryAjaxPostCreate(this);">
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Name" for="user-name"></label>
            <input asp-for="Name" id="user-name" type="text" autocomplete="off">
        </div>
        <span asp-validation-for="Name"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Surname" for="user-surname"></label>
            <input asp-for="Surname" id="user-surname" type="text" autocomplete="off">
        </div>
        <span asp-validation-for="Surname"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Patronymic" for="user-middlename"></label>
            <input asp-for="Patronymic" id="user-middlename" type="text" autocomplete="off">
            </div>
        <span asp-validation-for="Patronymic"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Email" for="user-email"></label>
            <input asp-for="Email" id="user-email" type="email" autocomplete="off">
        </div>
        <span asp-validation-for="Email"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Phone" for="user-number"></label>
            <input asp-for="Phone" id="user-number" type="text" autocomplete="off">
        </div>
        <span asp-validation-for="Phone"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="DepartmentsSelectList" for="user-division"></label>
            <select asp-for="Department.Id" asp-items="@Model.DepartmentsSelectList">
            </select>
        </div>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="RolesSelectList" for="user-role"></label>
            <select asp-for="Role.Id" asp-items="Model.RolesSelectList" id="user-role">
            </select>
        </div>
    </div>
    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="UserName" for="user-login"></label>
            <input asp-for="UserName" id="user-login" type="text" autocomplete="off">
        </div>
        <span asp-validation-for="UserName"></span>
    </div>

    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Password" for="user-password"></label>
            <input asp-for="Password" id="user-password" type="password" value="qwerty123" autocomplete="off">
        </div>
        <span asp-validation-for="Password"></span>
    </div>

    <div class="user__item">
        <div class="user__item-input">
            <label asp-for="Avatar" for="user-avatar"></label>
            <input asp-for="Avatar" id="user-avatar" type="file" class="form-control" />
            </div>
        <span asp-validation-for="Avatar"></span>
    </div>

    <div class="user__button">
        <button onclick="popupClose()" class="user__button-cancel">Отмена</button>
        <input type="submit" class="user__button-save" value="Сохранить">
    </div>
</form>

MiniSurveys.Web/Views/Admin/UserEditPartial.cshtml
@model MiniSurveys.Web.Models.UserView.UserEditViewModel

@{
    Layout = null;
}

<div class="user__header">
    <span class="user__title">Редактирование</span>
</div>
<form class="user__body" asp-action="UserEditPartial" enctype="multipart/form-data" onsubmit="return jQueryAjaxPost(this);">
    <input asp-for="Id" id="user-id" class="display-none" type="text">
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Name" for="user-name"></label>
        <input asp-for="Name" id="user-name" type="text">
        </div>
        <span asp-validation-for="Name"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Surname" for="user-surname"></label>
        <input asp-for="Surname" id="user-surname" type="text">
        </div>
        <span asp-validation-for="Surname"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Patronymic" for="user-middlename"></label>
        <input asp-for="Patronymic" id="user-middlename" type="text">
        </div>
        <span asp-validation-for="Patronymic"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Email" for="user-email"></label>
        <input asp-for="Email" id="user-email" type="email">
        </div>
        <span asp-validation-for="Email"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Phone" for="user-number"></label>
        <input asp-for="Phone" id="user-number" type="text">
        </div>
        <span asp-validation-for="Phone"></span>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="DepartmentsSelectList" for="user-division"></label>
        <select asp-for="Department.Id" asp-items="@Model.DepartmentsSelectList">
        </select>
        </div>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="RolesSelectList" for="user-role"></label>
        <select asp-for="Role.Id" asp-items="Model.RolesSelectList" id="user-role">
        </select>
        </div>
    </div>
    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="UserName" for="user-login"></label>
        <input asp-for="UserName" id="user-login" type="text">
        </div>
        <span asp-validation-for="UserName"></span>
    </div>

    <div class="user__item">
        <div class="user__item-input">
        <label asp-for="Avatar" for="user-avatar"></label>
        <input asp-for="Avatar" id="user-avatar" type="file" class="form-control" />
        </div>
        <span asp-validation-for="Avatar"></span>
    </div>

    <div class="user__button">
        <button onclick="popupClose()" class="user__button-cancel">Отмена</button>
        <input type="submit" class="user__button-save" value="Сохранить">
    </div>
</form>

MiniSurveys.Web/Views/Admin/UserListPartial.cshtml
@using MiniSurveys.Web.Models.UserView
@model IEnumerable<UserViewModel>

<table>
    <tr>
        <th>Логин</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>E-mail</th>
        <th>Телефон</th>
        <th>Подразделение</th>
        <th>Роль</th>
        <th><img src="../img/pridor.svg" alt=""></th>
    </tr>

    @foreach (var item in Model)
    {
        @await Component.InvokeAsync("RowUser", item)
    }
</table>

MiniSurveys.Web/Views/Admin/Users.cshtml
@using MiniSurveys.Web.Models.UserView
@model IEnumerable<UserViewModel>

<div class="main-body main__users">
    <div class="main-body__title title">
        <h1>Управление пользователями</h1>
    </div>
    <div class="main__searchandbutton ultrauser__searchandbutton">
        <button class="main__add" onclick="showInPopup('@Url.Action("UserCreatePartial","Admin", null, Context.Request.Scheme)')">+ Добавить</button>
        <div class="main__search">
            <input type="text" id="search-users">
            <img src="../img/search.svg" alt="">
        </div>
    </div>
    <div id="users-id" class="main__table">
        @await Html.PartialAsync("UserListPartial", Model)
    </div>
    <div class="popup">
        <div class="popup-body">
            <div class="popup-content">
            </div>
        </div>  
    </div>
</div>